name: "Lints"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

defaults:
  run:
    shell: bash

# do we really want nixos-unstable?
env:
  NIX_PATH: "nixpkgs=channel:nixos-unstable"
  REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deadnix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: |
          nix run github:astro/deadnix -- --edit --no-lambda-pattern-names
          TMPFILE=$(mktemp)
          git diff >"${TMPFILE}"
          git stash -u && git stash drop
          nix-shell -p reviewdog --run "reviewdog -f=diff -f.diff.strip=1 -reporter=github-pr-review < \"${TMPFILE}\""
